In deep learning, **optimizers** are algorithms that adjust the model’s parameters (weights and biases) to minimize the loss function during training.

Think of them as the *“steering wheel”* of the learning process — they decide **how to move through the loss landscape** to reach the lowest point.

---

## 1. What is Gradient Descent (GD)?

Gradient Descent is the **basic** optimizer.
It updates parameters like this:

$$
\theta_{\text{new}} = \theta_{\text{old}} - \eta \cdot \nabla_\theta \text{Loss}
$$

Where:

* $\theta$ = parameters
* $\eta$ = learning rate
* $\nabla_\theta \text{Loss}$ = gradient of the loss with respect to parameters

---

## 2. Why not just use GD for everything?

Vanilla GD is simple, but it has several **problems**:

| Problem with Plain GD                      | What it means                                                                            | Example                                                                      |
| ------------------------------------------ | ---------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------- |
| **Requires full dataset each step**        | In “batch GD”, you need all training data to compute one update — slow and memory-heavy. | If you have 10M images, you can’t wait for one giant gradient before moving. |
| **Same learning rate for all parameters**  | Can’t adapt to different parameter sensitivities.                                        | Some weights need big updates, others tiny.                                  |
| **Gets stuck in local minima or plateaus** | GD can hover around flat areas (saddle points).                                          | Deep nets have many such areas.                                              |
| **Sensitive to learning rate choice**      | Too big → overshoot, too small → slow convergence.                                       | Training either fails or takes ages.                                         |
| **No momentum**                            | Keeps “forgetting” past directions.                                                      | Like pushing a ball uphill without rolling advantage.                        |

---

## 3. Why we need *more* optimizers

Other optimizers are **variants of GD** that fix these weaknesses by adding extra ideas:

* **SGD (Stochastic Gradient Descent)** → Uses *mini-batches* to update faster and introduce randomness that helps escape local minima.
* **Momentum** → Adds velocity to updates so you can roll through small valleys.
* **RMSProp** → Adapts learning rate per parameter based on recent gradient sizes.
* **Adam** → Combines momentum + adaptive learning rates (very popular).
* **Adagrad / Adadelta** → Adjust learning rates based on frequency of parameter updates.
* **AdamW** → Adam + better weight decay for regularization.

---

### Analogy

Plain GD is like **walking straight toward the bottom** of a hill, always taking the same step size.
Modern optimizers are like **riding a bike with GPS**:

* Momentum = pedaling with stored speed
* RMSProp = changing speed based on road steepness
* Adam = both of the above, plus some tuning for each wheel separately

---


In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

# Dummy data: y = 2x + 1 (just for demo)
x = torch.randn(100, 1)
y = 2 * x + 1 + 0.1 * torch.randn(100, 1)  # add some noise

# Simple model
model = nn.Linear(1, 1)

# Loss function
criterion = nn.MSELoss()

# Choose optimizer: try changing to SGD, Adam, RMSprop etc.
optimizer = optim.Adam(model.parameters(), lr=0.1)
# optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
# optimizer = optim.RMSprop(model.parameters(), lr=0.1)

# Training loop
for epoch in range(50):
    # Forward pass
    y_pred = model(x)
    loss = criterion(y_pred, y)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/50], Loss: {loss.item():.4f}")

# Final parameters
print("Learned weight and bias:", list(model.parameters()))


Epoch [10/50], Loss: 0.0490
Epoch [20/50], Loss: 0.0892
Epoch [30/50], Loss: 0.0166
Epoch [40/50], Loss: 0.0189
Epoch [50/50], Loss: 0.0086
Learned weight and bias: [Parameter containing:
tensor([[1.9899]], requires_grad=True), Parameter containing:
tensor([1.0138], requires_grad=True)]


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

# Dummy data: y = 2x + 1 (just for demo)
x = torch.randn(100, 1)
y = 2 * x + 1 + 0.1 * torch.randn(100, 1)  # add some noise

# Simple model
model = nn.Linear(1, 1)

# Loss function
criterion = nn.MSELoss()

# Choose optimizer: try changing to SGD, Adam, RMSprop etc.
optimizer = optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
# optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
# optimizer = optim.RMSprop(model.parameters(), lr=0.1)

# Training loop
for epoch in range(50):
    # Forward pass
    y_pred = model(x)
    loss = criterion(y_pred, y)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/50], Loss: {loss.item():.4f}")

# Final parameters
print("Learned weight and bias:", list(model.parameters()))


Epoch [10/50], Loss: 0.2877
Epoch [20/50], Loss: 0.0123
Epoch [30/50], Loss: 0.0630
Epoch [40/50], Loss: 0.0500
Epoch [50/50], Loss: 0.0218
Learned weight and bias: [Parameter containing:
tensor([[2.0768]], requires_grad=True), Parameter containing:
tensor([1.0543], requires_grad=True)]


In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

# Dummy data: y = 2x + 1 (just for demo)
x = torch.randn(100, 1)
y = 2 * x + 1 + 0.1 * torch.randn(100, 1)  # add some noise

# Simple model
model = nn.Linear(1, 1)

# Loss function
criterion = nn.MSELoss()

# Choose optimizer: try changing to SGD, Adam, RMSprop etc.
optimizer = optimizer = optimizer = optim.RMSprop(model.parameters(), lr=0.1)
# optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
# optimizer = optim.RMSprop(model.parameters(), lr=0.1)

# Training loop
for epoch in range(50):
    # Forward pass
    y_pred = model(x)
    loss = criterion(y_pred, y)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/50], Loss: {loss.item():.4f}")

# Final parameters
print("Learned weight and bias:", list(model.parameters()))


Epoch [10/50], Loss: 0.0091
Epoch [20/50], Loss: 0.0091
Epoch [30/50], Loss: 0.0091
Epoch [40/50], Loss: 0.0091
Epoch [50/50], Loss: 0.0091
Learned weight and bias: [Parameter containing:
tensor([[1.9898]], requires_grad=True), Parameter containing:
tensor([1.0066], requires_grad=True)]




***

**Optimizers in Deep Learning**  
In the context of deep learning, **optimizers** are algorithmic strategies designed to update the trainable parameters of a neural network in order to minimize a given loss function. Formally, given a loss function $$ L(\theta) $$, where $$\theta$$ denotes the model parameters, an optimizer computes parameter updates to iteratively approach an optimal solution $$\theta^*$$.

***

### **Limitations of Basic Gradient Descent**  
The **gradient descent (GD)** method updates parameters according to:
$$
\theta_{t+1} = \theta_t - \eta \nabla_{\theta} L(\theta_t)
$$
where $$\eta$$ is the learning rate.

Despite its simplicity, gradient descent suffers from well-documented challenges:  
1. **Slow Convergence** — Fixed learning rates may result in prolonged optimization, particularly in regions with small gradient magnitudes.  
2. **Local Minima & Saddle Points** — High-dimensional loss landscapes often contain stationary points that slow or halt progress.  
3. **Oscillations** — In narrow valleys, large learning rates cause erratic movements across dimensions.  
4. **Learning Rate Sensitivity** — An improperly chosen $$\eta$$ may lead to divergence or suboptimal convergence.

***

### **Established Alternatives and Their Mechanisms**  

**1. Momentum (Polyak, 1964)**  
Incorporates a velocity term $$ v_t $$ to smooth updates:
$$
v_t = \beta v_{t-1} + (1 - \beta) \nabla_{\theta} L(\theta_t)  
\theta_{t+1} = \theta_t - \eta v_t
$$
This approach accelerates convergence in consistent gradient directions while reducing oscillatory behavior.

**2. Adagrad (Duchi et al., 2011)**  
Adapts learning rates per parameter based on accumulated squared gradients:
$$
\theta_{t+1} = \theta_t - \frac{\eta}{\sqrt{G_t + \epsilon}} \nabla_{\theta} L(\theta_t)
$$
where $$G_t$$ stores the sum of squared past gradients. Highly effective for sparse features.

**3. RMSProp (Hinton, 2012)**  
Normalizes learning rates by an exponentially weighted moving average of squared gradients:
$$
E[g^2]_t = \beta E[g^2]_{t-1} + (1 - \beta) (\nabla_{\theta} L(\theta_t))^2
$$
Improves stability on non-stationary objectives.

**4. Adam (Kingma & Ba, 2015)**  
Combines Momentum with RMSProp:
$$
m_t = \beta_1 m_{t-1} + (1 - \beta_1) g_t  
v_t = \beta_2 v_{t-1} + (1 - \beta_2) g_t^2  
\hat{m}_t = \frac{m_t}{1 - \beta_1^t}, \quad \hat{v}_t = \frac{v_t}{1 - \beta_2^t}  
\theta_{t+1} = \theta_t - \eta \frac{\hat{m}_t}{\sqrt{\hat{v}_t} + \epsilon}
$$
Adam provides robust performance across diverse architectures and datasets.

***

### **Empirical and Theoretical Support**  
- **Empirical evidence**: Numerous studies (e.g., on MNIST, CIFAR-10, ImageNet) demonstrate faster convergence and improved generalization when using advanced optimizers over vanilla GD.  
- **Theoretical analyses**: Convergence proofs exist for adaptive methods under convex optimization assumptions, with extensions to non-convex settings showing practical efficiency.  
- **Loss curve comparisons**: Visualizations consistently reflect reduced oscillations and faster descent when using Momentum-based or adaptive optimizers.

***

