In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print("GPU name: ", torch.cuda.get_device_name(0))
  print("GPU memory: ", torch.cuda.get_device_properties(0).total_memory)

GPU is available
GPU name:  Tesla T4
GPU memory:  15828320256


#creating Tensor

In [3]:
#using empty
x = torch.empty(3,3)
print(x)

tensor([[ 1.5206e-38,  0.0000e+00,  9.1084e-44],
        [ 0.0000e+00, -4.5183e-14,  4.3721e-41],
        [-4.5183e-14,  4.3721e-41,  1.6326e-38]])


In [4]:
#using empty and check type
type(x)

torch.Tensor

In [5]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using rand
torch.rand(2,3)

tensor([[0.6490, 0.2113, 0.2174],
        [0.1775, 0.6483, 0.7898]])

In [8]:
#using of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [9]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [12]:
#using tensor
torch.tensor([[1,24],[3,4]])

tensor([[ 1, 24],
        [ 3,  4]])

In [16]:
#other ways

torch.arange(0,10,2)
torch.linspace(0,10,5)
torch.eye(5)
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

#Tensor shapes

In [23]:
x  = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)

In [18]:
x.shape


torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[35639638622208,              0,              0],
        [             0,              0,             81]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
torch.rand_like(x)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

#Tensor Data Types

In [25]:
x.dtype

torch.float32

In [26]:
torch.tensor([1,3,4],dtype=torch.float32)

tensor([1., 3., 4.])

In [27]:
torch.tensor([1,3.0,4],dtype=torch.int)

tensor([1, 3, 4], dtype=torch.int32)

In [28]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [29]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

#Math operations

In [32]:
#scalar operations
x = torch.rand(3,3)
print(x)

tensor([[0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])


In [33]:
x+2

tensor([[2.1994, 2.5472, 2.0062],
        [2.9516, 2.0753, 2.8860],
        [2.5832, 2.3376, 2.8090]])

In [34]:
x-3

tensor([[-2.8006, -2.4528, -2.9938],
        [-2.0484, -2.9247, -2.1140],
        [-2.4168, -2.6624, -2.1910]])

In [35]:
x*4

tensor([[0.7975, 2.1888, 0.0246],
        [3.8062, 0.3011, 3.5441],
        [2.3328, 1.3506, 3.2359]])

In [36]:
x /3

tensor([[0.0665, 0.1824, 0.0021],
        [0.3172, 0.0251, 0.2953],
        [0.1944, 0.1125, 0.2697]])

In [37]:
(x*100)//3

tensor([[ 6., 18.,  0.],
        [31.,  2., 29.],
        [19., 11., 26.]])

In [38]:
((x*100)//3)%2

tensor([[0., 0., 0.],
        [1., 0., 1.],
        [1., 1., 0.]])

In [39]:
x**2

tensor([[3.9746e-02, 2.9942e-01, 3.7951e-05],
        [9.0546e-01, 5.6650e-03, 7.8502e-01],
        [3.4013e-01, 1.1401e-01, 6.5444e-01]])

#Element wise operations

In [40]:
a = torch.rand(3,3)
b = torch.rand(3,3)

In [41]:
a+b

tensor([[0.8593, 1.6926, 1.1441],
        [1.0962, 0.8296, 0.3695],
        [1.0172, 1.0629, 1.6993]])

In [42]:
a-b

tensor([[ 0.2965,  0.1153, -0.0348],
        [-0.4116,  0.4391,  0.3594],
        [ 0.4036,  0.8299, -0.1212]])

In [43]:
a*b

tensor([[0.1626, 0.7129, 0.3270],
        [0.2581, 0.1239, 0.0018],
        [0.2180, 0.1102, 0.7182]])

In [44]:
a**b

tensor([[0.8570, 0.9235, 0.7065],
        [0.4457, 0.9150, 0.9949],
        [0.9004, 0.9936, 0.8060]])

In [45]:
a/b

tensor([[ 2.0537,  1.1463,  0.9410],
        [ 0.4540,  3.2489, 72.2209],
        [ 2.3155,  8.1245,  0.8668]])

In [46]:
a%b

tensor([[0.0151, 0.1153, 0.5547],
        [0.3423, 0.0486, 0.0011],
        [0.0968, 0.0145, 0.7890]])

In [47]:
c = torch.tensor([1,-3,4,-3])

In [48]:
torch.abs(c)

tensor([1, 3, 4, 3])

In [49]:
torch.neg(c)

tensor([-1,  3, -4,  3])

In [50]:
d = torch.tensor([1.3,3.5,5.3,3])

In [51]:
torch.round(d)

tensor([1., 4., 5., 3.])

In [52]:
torch.ceil(d)

tensor([2., 4., 6., 3.])

In [53]:
torch.floor(c)

tensor([ 1, -3,  4, -3])

In [54]:
#clamp
torch.clamp(d,min=2,max=4)

tensor([2.0000, 3.5000, 4.0000, 3.0000])

#Reduction operations

In [62]:
e = torch.randint(size = (2,3),low=0,high= 10,dtype = torch.float32)
e

tensor([[6., 0., 0.],
        [0., 0., 1.]])

In [63]:
#sum
torch.sum(e)

tensor(7.)

In [64]:
torch.sum(e,dim=0)

tensor([6., 0., 1.])

In [65]:
torch.sum(e,dim=1)

tensor([6., 1.])

In [66]:
torch.mean(e)

tensor(1.1667)

In [68]:
torch.mean(e,dim=0)

tensor([3.0000, 0.0000, 0.5000])

In [69]:
torch.mean(e,dim=1)

tensor([2.0000, 0.3333])

In [70]:
torch.median(e)

tensor(0.)

In [71]:
torch.max(e)
torch.min(e)

tensor(0.)

In [72]:
torch.std(e)

tensor(2.4014)

In [73]:
torch.prod(e)

tensor(0.)

In [74]:
torch.var(e)

tensor(5.7667)

In [75]:
torch.argmax(e)

tensor(0)

In [77]:
torch.argmin(e)

tensor(1)

In [78]:
torch.matmul(a,b)

tensor([[1.0143, 0.6969, 0.8501],
        [0.6864, 0.4363, 0.5367],
        [1.1555, 0.8370, 1.1418]])

In [ ]:
torch.dot(a,b)

In [82]:
torch.transpose(e,0,1)

tensor([[6., 0.],
        [0., 0.],
        [0., 1.]])

In [84]:
torch.det(a)

tensor(0.0095)

In [85]:
torch.inverse(a)

tensor([[ 16.3052, -19.7311,  -2.3493],
        [ -1.1742,   6.4908,  -2.1723],
        [-13.2725,   9.9801,   5.9882]])

In [86]:
a>b

tensor([[ True,  True, False],
        [False,  True,  True],
        [ True,  True, False]])

In [87]:
a==b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [88]:
a<b

tensor([[False, False,  True],
        [ True, False, False],
        [False, False,  True]])

In [89]:
a!=b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [90]:
torch.log(a)

tensor([[-0.5483, -0.1009, -0.5894],
        [-1.0720, -0.4552, -1.0095],
        [-0.3419, -0.0551, -0.2370]])

In [91]:
torch.exp(a)

tensor([[1.7823, 2.4694, 1.7413],
        [1.4082, 1.8858, 1.4397],
        [2.0349, 2.5764, 2.2013]])

In [92]:
torch.sqrt(a)

tensor([[0.7602, 0.9508, 0.7448],
        [0.5851, 0.7965, 0.6037],
        [0.8429, 0.9728, 0.8883]])

In [93]:
torch.softmax(a,dim = 0)

tensor([[0.3411, 0.3563, 0.3235],
        [0.2695, 0.2721, 0.2675],
        [0.3894, 0.3717, 0.4090]])

In [94]:
torch.relu(a)

tensor([[0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])

In [96]:
a.relu_()

tensor([[0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])

In [97]:
b = a.clone()

In [98]:
id(a)


134000604113216

In [99]:
id(b)

134000603382160

In [100]:
torch.cuda.is_available()

True

In [101]:
device =torch.device('cuda')

In [102]:
torch.rand((2,3),device =device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [103]:
b =a.to(device)

In [104]:
a.flatten()

tensor([0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890])

In [105]:
import numpy as np
a = torch.tensor([1,2,3])

In [106]:
b = a.numpy()

In [107]:
type(b)

numpy.ndarray

In [108]:
c = np.array([1,2,3])

In [110]:
torch.from_numpy(c)

tensor([1, 2, 3])