In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available ,using CPU")

GPU is available
Using GPU: Tesla T4


##Creating a Tensor

In [3]:
#using empty
a = torch.empty(2,3)

In [4]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
#check type
type(a)


torch.Tensor

In [6]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using rand
torch.rand(2,3)

tensor([[0.7089, 0.6806, 0.8731],
        [0.8049, 0.9245, 0.5629]])

In [9]:
#using manual_seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [10]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [11]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
#other ways

#arange
print("using arange ->",torch.arange(1,10,2))
#linspace
print("using linspace ->",torch.linspace(1,10,10))
#eye
print("using eye ->",torch.eye(5))
#full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([1, 3, 5, 7, 9])
using linspace -> tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[140533332995472, 140533332995472,               0],
        [              0,               0,               0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x,dtype = torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

##Tensor Data Types

In [19]:
#find data type
x.dtype

torch.int64

In [20]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1,2,3],dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [22]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


#Mathematical Operations

###Scalar operation

In [23]:
x = torch.rand(2,2)
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [24]:
#addition
x+3
#subtraction
x -2
#multiplication
x * 3
#division
x/3
#int division
(x*100)//3
#mod
((x*100)//3)%2
#power
x**2

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])

#Element wise operation

In [25]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])
tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])


In [26]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.2916, 0.5739, 0.0560],
        [0.0885, 0.2696, 0.0426]])

In [27]:
c = torch.tensor([1,-2,3,-4])


In [28]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [29]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [30]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [31]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [32]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [33]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [34]:
#clamp
torch.clamp(d,min = 2,max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

#Reduction Operation

In [35]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 9., 2.],
        [0., 5., 9.]])

In [36]:
from functools import total_ordering
#sum
torch.sum(e)
#sum along columns
torch.sum(e,dim = 0)
#sum along rows
torch.sum(e,dim = 1)

tensor([18., 14.])

In [37]:
#mean
torch.mean(e)
#mean along col
torch.mean(e,dim =0)
#mean along row
torch.mean(e,dim =1)

tensor([6.0000, 4.6667])

In [38]:
#median
torch.median(e)
#median along col
torch.median(e,dim =0)
#median along row
torch.median(e,dim =1)

torch.return_types.median(
values=tensor([7., 5.]),
indices=tensor([0, 1]))

In [39]:
#max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [40]:
# product
torch.prod(e)

tensor(0.)

In [41]:
# standard deviation
torch.std(e)

tensor(3.7238)

In [42]:
# variance
torch.var(e)

tensor(13.8667)

In [43]:
#argmax
torch.argmax(e)


tensor(1)

In [44]:
#argmin
torch.argmin(e)

tensor(3)

##Matrix operations

In [45]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 4, 9],
        [6, 2, 0]])
tensor([[6, 2],
        [7, 9],
        [7, 3]])


In [46]:
#matrix multiplication
print(torch.matmul(f,g))
print(f @ g)

tensor([[109,  69],
        [ 50,  30]])
tensor([[109,  69],
        [ 50,  30]])


In [47]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [48]:
#transpose
torch.transpose(f,0,1)

tensor([[3, 6],
        [4, 2],
        [9, 0]])

In [49]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 4., 3.],
        [7., 0., 9.],
        [0., 9., 6.]])

In [50]:
#determinant
torch.det(h)

tensor(-222.)

In [51]:
#inverse
torch.inverse(h)

tensor([[ 0.3649, -0.0135, -0.1622],
        [ 0.1892, -0.0811,  0.0270],
        [-0.2838,  0.1216,  0.1261]])

##Comparison Operations


In [52]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 5, 4],
        [8, 8, 6]])
tensor([[0, 0, 0],
        [0, 1, 3]])


In [53]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j

# less than equal to
i <= j

tensor([[False, False, False],
        [False, False, False]])

#Special Functions

In [54]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 1., 1.],
        [7., 9., 4.]])

In [55]:
# log
torch.log(k)

tensor([[  -inf, 0.0000, 0.0000],
        [1.9459, 2.1972, 1.3863]])

In [56]:
#exp
torch.exp(k)

tensor([[1.0000e+00, 2.7183e+00, 2.7183e+00],
        [1.0966e+03, 8.1031e+03, 5.4598e+01]])

In [57]:
#sqrt
torch.sqrt(k)

tensor([[0.0000, 1.0000, 1.0000],
        [2.6458, 3.0000, 2.0000]])

In [58]:
#sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.7311, 0.7311],
        [0.9991, 0.9999, 0.9820]])

In [59]:
#softmax
torch.softmax(k,dim =0)

tensor([[9.1105e-04, 3.3535e-04, 4.7426e-02],
        [9.9909e-01, 9.9966e-01, 9.5257e-01]])

In [60]:
#relu
torch.relu(k)

tensor([[0., 1., 1.],
        [7., 9., 4.]])

##Inplace Operations

In [61]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790]])
tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])


In [62]:
m.add_(n)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [63]:
m

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [64]:
n

tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])

In [65]:
torch.relu(m)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [66]:
m.relu_()

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [67]:
m

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

#Copying a Tensor

In [68]:
a = torch.rand(2,3)
a

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [69]:
b = a

In [70]:
b

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [71]:
a[0][0] = 0

In [72]:
a

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [73]:
b

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [74]:
id(a)

140529430165456

In [75]:
id(b)

140529430165456

In [76]:
b = a.clone()

In [77]:
a

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [78]:
b

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [79]:
a[0][0] = 10

In [80]:
a

tensor([[10.0000,  0.7860,  0.1115],
        [ 0.2477,  0.6524,  0.6057]])

In [81]:
b

tensor([[0.0000, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [82]:
id(a)

140529430165456

In [83]:
id(b)

140529430287600

#Tensor Operations on GPU

In [84]:
torch.cuda.is_available()

True

In [88]:
device = torch.device('cuda')

In [89]:
#creating a new tensor on GPU
torch.rand(2,3,device = devie)

tensor([[0.9877, 0.1289, 0.5621],
        [0.5221, 0.7445, 0.5955]], device='cuda:0')

In [90]:
 #moving an existing tensor to GPU
 b =a.to(device)

In [91]:
b+4

tensor([[14.0000,  4.7860,  4.1115],
        [ 4.2477,  4.6524,  4.6057]], device='cuda:0')

In [92]:
import torch
import time

# Set the size of the matrices
matrix_size = 10000 # You can adjust this size for larger or smaller matrices

# Create random matrices
A = torch.rand(matrix_size, matrix_size)
B = torch.rand(matrix_size, matrix_size)

# Function to perform matrix multiplication on CPU
def cpu_matrix_multiplication(A, B):
    start_time = time.time()
    C = A @ B  # Matrix multiplication
    end_time = time.time()
    return C, end_time - start_time

# Function to perform matrix multiplication on GPU
def gpu_matrix_multiplication(A, B):
    A_gpu = A.to('cuda')  # Move matrix A to GPU
    B_gpu = B.to('cuda')  # Move matrix B to GPU
    start_time = time.time()
    C_gpu = A_gpu @ B_gpu  # Matrix multiplication
    torch.cuda.synchronize()  # Wait for all operations to finish
    end_time = time.time()
    return C_gpu, end_time - start_time

# Perform matrix multiplication on CPU
C_cpu, cpu_time = cpu_matrix_multiplication(A, B)
print(f"CPU Time: {cpu_time:.6f} seconds")

# Perform matrix multiplication on GPU (if available)
if torch.cuda.is_available():
    C_gpu, gpu_time = gpu_matrix_multiplication(A, B)
    print(f"GPU Time: {gpu_time:.6f} seconds")
else:
    print("GPU is not available.")


CPU Time: 29.833278 seconds
GPU Time: 0.693882 seconds


#Reshape Tensors

In [107]:
import torch

# Create a tensor with shape (2, 2, 2, 2)
a = torch.rand(2, 2, 2, 2)  # This creates a tensor with 16 elements

# Reshape the tensor to a different shape
reshaped_tensor = a.reshape(4, 4)  # Reshaping to (4, 4)

# Print the original and reshaped tensor shapes
print("Original shape:", a.shape)  # Output: torch.Size([2, 2, 2, 2])
print("Reshaped shape:", reshaped_tensor.shape)  # Output: torch.Size([4, 4])


Original shape: torch.Size([2, 2, 2, 2])
Reshaped shape: torch.Size([4, 4])


In [96]:
a.flatten()

tensor([10.0000,  0.7860,  0.1115,  0.2477,  0.6524,  0.6057])

In [100]:
b = torch.rand(2,3,4)
b.shape

torch.Size([2, 3, 4])

In [99]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [101]:
#unsqueeze
#image size
c = torch.rand(226,226,3)
c.unsqueeze(dim = 0).shape

torch.Size([1, 226, 226, 3])

In [103]:
import torch

# Create a 1D tensor
tensor_1d = torch.tensor([1, 2, 3, 4])
print("Original 1D Tensor:", tensor_1d)
print("Shape:", tensor_1d.shape)  # Output: torch.Size([4])

# Unsqueeze to add a dimension at index 0
tensor_2d = torch.unsqueeze(tensor_1d, 0)
print("Unsqueezed Tensor (dim=0):", tensor_2d)
print("Shape:", tensor_2d.shape)  # Output: torch.Size([1, 4])

# Unsqueeze to add a dimension at index 1
tensor_2d_2 = torch.unsqueeze(tensor_1d, 1)
print("Unsqueezed Tensor (dim=1):", tensor_2d_2)
print("Shape:", tensor_2d_2.shape)  # Output: torch.Size([4, 1])


Original 1D Tensor: tensor([1, 2, 3, 4])
Shape: torch.Size([4])
Unsqueezed Tensor (dim=0): tensor([[1, 2, 3, 4]])
Shape: torch.Size([1, 4])
Unsqueezed Tensor (dim=1): tensor([[1],
        [2],
        [3],
        [4]])
Shape: torch.Size([4, 1])


In [105]:
import torch

# Create a tensor with shape (1, 20)
d = torch.rand(1, 20)

# Squeeze the tensor to remove the dimension of size 1
squeezed_tensor = d.squeeze(0)

# Print the shape of the squeezed tensor
print(squeezed_tensor.shape)


torch.Size([20])


#Numpy and PyTorch

In [108]:
import numpy as np



In [109]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [110]:
b = a.numpy()

In [111]:
b

array([1, 2, 3])

In [112]:
type(b)

numpy.ndarray

In [113]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [114]:
torch.from_numpy(c)

tensor([1, 2, 3])